UnmarshalKey: foodi-dev/foodi-user-service # consul 配置文件 key
Consul:
  Host: 8.134.206.241:8500 # consul 节点列表
  Token: "" # 集群开启ACL后需要配置
  Key: foodi-user-service.rpc # 注册到consul的key
  Meta:
    Protocol: grpc
  Tag: # 注册到 consul 的标签,多个以逗号隔开
    - foodi-user-service
    - rpc