// Code generated by goctl. DO NOT EDIT.
// Source: foodiUserService.proto

package server

import (
	"context"

	"github.com/foodi-org/foodi-user-service/internal/logic/user"
	"github.com/foodi-org/foodi-user-service/internal/svc"
	"github.com/foodi-org/foodi-user-service/pb/github.com/foodi-org/foodi-user-service"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	foodi_user_service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) BaseInfo(ctx context.Context, in *foodi_user_service.UserRequest) (*foodi_user_service.UserReply, error) {
	l := userlogic.NewBaseInfoLogic(ctx, s.svcCtx)
	return l.BaseInfo(in)
}

func (s *UserServer) DetailInfo(ctx context.Context, in *foodi_user_service.UserDetailRequest) (*foodi_user_service.UserDetailReply, error) {
	l := userlogic.NewDetailInfoLogic(ctx, s.svcCtx)
	return l.DetailInfo(in)
}
